apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-nodejs
    app.kubernetes.io/part-of: purple-mermaid-app
  name: hacbs-nodejs
  namespace: karthik-jk
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hacbs-nodejs
    weight: 100
status: {}
