apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: new-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: new-quarkus
    app.kubernetes.io/part-of: purple-mermaid-app
  name: new-quarkus
  namespace: karthik-jk
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: new-quarkus
    weight: 100
status: {}
